export const data = [
  {
    id: 1,
    name: 'Alieksieiev Vladyslav',
    avatar: 'https://i.postimg.cc/D0TYJ5dS/photo-2022-09-30-15-13-28.jpg',
    rating: 5,
    text: 'Noting your successes and achievements is important to maintain motivation and development in your chosen field.',
  },
  {
    id: 2,
    name: 'Averkin Maksym',
    avatar: 'https://i.postimg.cc/C1VRWfsG/i.webp',
    rating: 5,
    text: '“To understand the mid code, you have to be mid.  To understand the code of a senior, it is enough to be a junior.” Gabe Logan Newell',
  },
  {
    id: 3,
    name: 'Vyshnevska Maryna',
    avatar: 'https://i.postimg.cc/NfDF8zsQ/IMG-0999.jpg',
    rating: 5,
    text: 'I thank Goit and our mentors for their support! And now I can say that I know what a dream team is! This is our team! I wish everyone to find the best job in their lives and be happy!',
  },
  {
    id: 4,
    name: 'Pysarenko Tetiana',
    avatar: 'https://i.postimg.cc/TYDQpnfj/photo-2023-05-03-19-42-49.jpg',
    rating: 5,
    text: "It's been an interesting year! Thanks to everyone! Choose a job to your liking, and you won't have to work a single day in your life. - Confucius.",
  },
  {
    id: 5,
    name: 'Podoliako Oleksandr',
    avatar: 'https://i.postimg.cc/2yV6ZJJP/px1-O47txy3-I.jpg',
    rating: 5,
    text: 'Success is the ability to move from failure to failure without losing enthusiasm. W. Churchill',
  },
  {
    id: 6,
    name: 'Yurov Igor',
    avatar: 'https://i.postimg.cc/d0WbQGjR/photo-2020-04-27-22-21-36.jpg',
    rating: 5,
    text: 'I wish that your sleep is always sound and healthy, and that coding brings you joy and fulfillment, embodying your ideas into greatness!',
  },
  {
    id: 7,
    name: 'Lipchanskyi Pavlo',
    avatar: 'https://i.postimg.cc/RVL6s0R5/photo-2-2023-05-03-19-37-48.jpg',
    rating: 5,
    text: 'Wish everyone to find your guiding star, that makes you move on!',
  },
  {
    id: 8,
    name: 'Ivan Koshel',
    avatar: 'https://i.postimg.cc/j2XxXDrM/photo-3-2023-05-03-19-37-48.jpg',
    rating: 5,
    text: 'Sleep is a blessing, but writing code is an embodiment of magnificence!',
  },
  {
    id: 9,
    name: 'Litvin Serhii',
    avatar: 'https://i.postimg.cc/3NCq0pHx/photo-2023-05-03-19-48-04.jpg',
    rating: 5,
    text: "The one who does nothing makes no mistakes. Don't be afraid to make mistakes - be afraid to repeat mistakes.— Theodore Roosevelt.",
  },
  {
    id: 10,
    name: 'Vyshnevska Maryna',
    avatar: 'https://i.postimg.cc/NfDF8zsQ/IMG-0999.jpg',
    rating: 5,
    text: 'I thank Goit and our mentors for their support! And now I can say that I know what a dream team is! This is our team! I wish everyone to find the best job in their lives and be happy!',
  },
];
